# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Libraries and Digital Humanities
tagline:          'An Alliance of Digital Humanities Special Interest Group'
description:      'The <a href="https://adho.org">Alliance of Digital Humanities</a> Special Interest Group where Digital Humanities and Libraries meet'
url:              https://adholibdh.github.io
baseurl:          /

author:
  name:
  url:            https://twitter.com/LibsDH

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adholibdh

# Plugins
plugins: [jekyll-paginate]
