# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ADHO Libraries and DH SIG
tagline:          'A site for Digital Humanities and Libraries'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ADHOLibDH.github.io
baseurl:          /

author:
  name:           'Zoe Borovsky'
  url:            https://twitter.com/LibsDH

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ADHOLibDH

# Plugins
gems: [jekyll-paginate]
